### ISSUE TITLE
tcpoutput and tcpinput problem

### ISSUE THREAD

**Issue by jkpol** [mozilla-services/heka#1575] opened 2015-06-19 19:44 UTC
Hi, my use case is: in the client use Logstreamer Input to collect log, and use TCP Output to send the log to center log collect server.At the center log collect server use TCP Input to collect the log.But there is a problem, when i use kill to kill the server's heka process and restart heka,the client's heka will lost a message.I can see that,when i kill the server's heka,the client's TCP Input do not find the server is closed,So it send messages to the server,and at the first one the client return no err.At that time,when close the server heka,i cant see that,the socket is CLOSE_WAIT,but client's TCP Output do not find the server is close.
I think maybe we can use a goroutine to read the tcp connect,so that it can find the connect is close.But the write goroutine and check goroutine is no explicit which one will execute first.If the write goroutine execute first that will lost one message.
This is a typical use case,restart on server is normal thing.So how can i do in this case?

**Comment by trink** [comment] 2015-06-19 19:55
Duplicate of https://github.com/mozilla-services/heka/issues/1213

**Closed by trink** 2015-06-19 19:55 UTC

**Comment by jkpol** [comment] 2015-06-20 03:50
Thanks,get it.
