### ISSUE TITLE
write_message can't overwrite field of different type

### ISSUE THREAD

**Issue by hobofan** [mozilla-services/heka#1295] opened 2015-01-29 20:12 UTC
While trying to convert some fields from string to int in a lua decoder I noticed that it is not possible to overwrite a field with a value of a different type. 

This is the error being thrown:
```
 decode error: FATAL: process_message() /usr/share/heka/lua_decoders/intify.lua:38: write_message() failed
```

**Comment by rafrombrc** [comment] 2015-02-28 01:35
This is intended behavior. I've finished and merged your delete fields patch, so this should be resolved.

**Closed by rafrombrc** 2015-02-28 01:35 UTC
