### ISSUE TITLE
ProcessInput does not work with long running processes in 0.10.0b0

### ISSUE THREAD

**Issue by timurb** [mozilla-services/heka#1644] opened 2015-07-29 13:02 UTC
I'm running Heka 0.10.0.b0 on Ubuntu Precise and it looks like ProcessInput does not work with long processes.

I'm using the following config:

```
[hekad]
maxprocs = 2

[DashboardOutput]
ticker_interval = 5

[debug_encoder]
type="RstEncoder"

[LogOutput]
message_matcher = "TRUE"
encoder = "debug_encoder"

[process]
type = "ProcessInput"
ticker_interval = 0
splitter = "on_space"
stdout = true
stderr = false

[process.command.0]
bin = "/usr/local/bin/ticker"

[on_space]
type = "TokenSplitter"
delimiter = " "
```

The `ticker` is a simple script which outputs increasing numbers delimited by space.
```
#!/bin/sh
x=1
while true; do
  echo -n "$x "
  sleep 1
  x=$(($x + 1))
done
```
I would expect to see the messages of type ProcessInput emitted every second but I see no such messages in the output.

If I change the ticker script into a simple
```
#!/bin/sh

echo 1
```
and set `ticker_interval = 0` in heka config all appears to be working fine.

I've tried the same in v0.9.2 and it looks like this issue can be seen only in 0.10

**Comment by simonpasquier** [comment] 2015-07-30 09:58
Could it be related with #1620?

**Comment by timurb** [comment] 2015-07-30 10:20
@simonpasquier does it say that TokenSplitter works incorrectly?
Probably, I haven't checked that with disabling splitter (as it has little sense for long-running input).
On the other hand I think I have not disabled splitter when I used a single-run version of ticker and all was ok (I'm not completely sure in this).

**Comment by simonpasquier** [comment] 2015-07-30 10:26
AFAICT with 0.10, ProcessInput doesn't work properly with TokenSplitter (and maybe other splitters too). Only the first output of the command may be passed to the decoder and then the Heka pipeline but that's all.

**Comment by rafrombrc** [comment] 2015-08-02 19:08
The code from #1648 has been merged to both dev and versions/0.10 branches. Any chance you can build from the versions/0.10 branch and test to see if the issue is indeed resolved? Thanks!

**Comment by timurb** [comment] 2015-08-03 07:49
@rafrombrc Looks fine to me in this build.

**Comment by rafrombrc** [comment] 2015-08-03 17:39
Great, thanks, closing this issue.

**Closed by rafrombrc** 2015-08-03 17:39 UTC
