### ISSUE TITLE
Support new InfluxDB 0.9.x line protocol write API

### ISSUE THREAD

**Issue by acesaro** [mozilla-services/heka#1564] opened 2015-06-08 19:54 UTC
Well, it looks like they've decided to change the default format for the write API, per this PR: https://github.com/influxdb/influxdb/pull/2696.  I'm logging this here to follow up on updating the functionality of the Schema InfluxDB Write Encoder to support this as the JSON format will eventually be deprecated and this provides better performance anyway.

**Comment by syepes** [comment] 2015-06-08 21:22
+1

**Comment by jpgnz** [comment] 2015-06-09 02:02
+1

**Comment by LordFPL** [comment] 2015-06-09 05:15
+1

**Comment by mjseid** [comment] 2015-06-13 15:49
+1

**Comment by steverweber** [comment] 2015-06-16 03:21
+1

**Comment by acesaro** [comment] 2015-06-18 04:49
PR submitted for this updated functionality: https://github.com/mozilla-services/heka/pull/1574

**Comment by acesaro** [comment] 2015-06-19 17:11
I've made some comments in that PR and closed it.  A better approach is going to be taken that encouraged code reuse, so I'll comment here again when that is available in a PR for testing and eventually merged into the project.

**Comment by acesaro** [comment] 2015-07-02 03:26
I finally got around to an initial implementation for this in PR https://github.com/mozilla-services/heka/pull/1595.  This also includes a new Schema Carbon Line Encoder which uses very similar functionality and allows us to integrate with Graphite in a similar manner.  Feedback on that PR is welcome.

**Comment by steverweber** [comment] 2015-07-16 23:11
missing help for new line encoder:
http://hekad.readthedocs.org/en/v0.10.0b0/config/encoders/schema_influx_write.html#config-schema-influx-write-encoder

**Comment by steverweber** [comment] 2015-07-16 23:39
probably doing something silly wrong, but I cant seem to get this to work:

installed influxdb 9.1 using default settings.
opened: http://127.0.0.1:8083
created database : woot


installed heka 
`
wget https://github.com/mozilla-services/heka/releases/download/v0.10.0b0/heka_0.10.0b0_amd64.deb
sudo pkg -i heka_0.10.0b0_amd64.deb
`

vi /etc/heka/conf.d/01-test.toml
```
[DashboardOutput]
ticker_interval = 1

[LoadAvgPoller]
type = "FilePollingInput"
ticker_interval = 5
file_path = "/proc/loadavg"
decoder = "LinuxStatsDecoder"

[LoadAvgDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_loadavg.lua"

[LinuxStatsDecoder]
type = "MultiDecoder"
subs = ["LoadAvgDecoder", "AddStaticFields"]
cascade_strategy = "all"
log_sub_errors = false

[AddStaticFields]
type = "ScribbleDecoder"
        [AddStaticFields.message_fields]
        Environment = "dev"

[InfluxdbLineEncoder]
type = "SandboxEncoder"
filename = "lua_encoders/schema_influx_line.lua"

        [InfluxdbLineEncoder.config]
        skip_fields = "**all_base** FilePath NumProcesses Environment TickerInterval"
        tag_fields = "Hostname Environment"
        timestamp_precision= "s"

[InfluxdbOutput]
type = "HttpOutput"
message_matcher = "Type =~ /stats.*/"
encoder = "InfluxdbLineEncoder"
username = "admin"
password = "admin"
address = "http://127.0.0.1:8086/write?db=woot&precision=s"
```
restarted heka service...

watched heka dashboard ... http://127.0.0.1:4352
looks to be doing stuff.
 InfluxdbOutput-InfluxdbLineEncoder processed 74...

returned to (http://127.0.0.1:8083)influxdb  and tried to find the data...  but with no luck...

thoughts?

**Comment by rafrombrc** [comment] 2015-07-16 23:44
This isn't really the best venue for such questions, the mailing list is better for support requests like this. We're not actually using Influx at Mozilla, so I'd have to set up a rig to test this, but for debugging I'd recommend breaking your experiment into two parts. First you can replace the HttpOutput with a LogOutput using the same encoder; this will show you exactly what is going in to the HTTP requests that the HttpOutput would be making. Then you can try to use curl or some other HTTP tool to send that output into InfluxDB, to see if you can get the data in directly.

**Comment by steverweber** [comment] 2015-07-16 23:49
thanks for the debug hint @rafrombrc.  Perhaps @acesaro has a hint because I'm using basically the same config that was found in the example for schema_influx_line.lua
.
Once i get this to work I can confirm this issue is resolved and can be closed :)

**Comment by mjseid** [comment] 2015-07-17 00:28
@steverweber I can confirm this works (I've been using successfully for about a week now with a minor tweak to batch up writes).  Here's the relevant parts from my config, other than the db creds looks like the only real difference is I'm specifying retention policy in my write command.
```
[influxdb-encoder-cf-np]
type = "SandboxEncoder"
filename = "lua_encoders/schema_influx_line.lua"

    [influxdb-encoder-cf-np.config]
    skip_fields = "**all_base** Env IP Index Job Metric"
    tag_fields = "Job Index IP"
    timestamp_precision= "s"

[influxdb-output-cf-np]
type = "HttpOutput"
message_matcher = "Type == 'CFCollector' &&  Fields[Env] == 'cf-np' "
address = "http://influxdb:8086/write?db=cf_np&rp=default&precision=s"
username = "root"
password = "root"
encoder = "influxdb-encoder-cf-np"
```

Also as suggested you can use these settings to send everything from Heka to the log file to potentially get more info....

```
[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"
```

**Comment by steverweber** [comment] 2015-07-17 00:33
I check LogOutput with a PayloadEncoder and only get blank lines... so the problem is likely not the InfluxdbLineEncoder or the example... just me

Thanks for confirming my config looks fine!

**Comment by rafrombrc** [comment] 2015-07-17 00:38
I actually meant you could try LogOutput with InfluxdbLineEncoder so you can see the output that the Influx decoder is generating, like so:
```toml
[LogOutput]
message_matcher = "Type =~ /stats.*/"
encoder = "InfluxdbLineEncoder"
```
Getting blank lines w/ a PayloadEncoder just means that you're getting messages with no payload, which isn't necessarily a problem, since the message's data may be stored in other fields.

**Comment by steverweber** [comment] 2015-07-17 00:47
@rafrombrc  yes that was what i tried first before just using the PayloadEncoder.

full config
```
[hekad]
maxprocs = 2

#[TcpInput]
#address = "127.0.0.1:5565"

#[StatAccumInput]

[DashboardOutput]
ticker_interval = 1

[LoadAvgPoller]
type = "FilePollingInput"
ticker_interval = 5
file_path = "/proc/loadavg"
decoder = "LinuxStatsDecoder"

[LoadAvgDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_loadavg.lua"

[LinuxStatsDecoder]
type = "MultiDecoder"
subs = ["LoadAvgDecoder", "AddStaticFields"]
cascade_strategy = "all"
log_sub_errors = false

[AddStaticFields]
type = "ScribbleDecoder"
        [AddStaticFields.message_fields]
        Environment = "dev"

[InfluxdbLineEncoder]
type = "SandboxEncoder"
filename = "lua_encoders/schema_influx_line.lua"

        [InfluxdbLineEncoder.config]
        skip_fields = "**all_base** FilePath NumProcesses Environment TickerInterval"
        tag_fields = "Hostname Environment"
        timestamp_precision= "s"

[LogOutput]
message_matcher = "Type =~ /stats.*/"
encoder = "InfluxdbLineEncoder"

#[InfluxdbOutput]
#type = "HttpOutput"
#message_matcher = "Type =~ /stats.*/"
#encoder = "InfluxdbLineEncoder"
#username = "admin"
#password = "admin"
#address = "http://127.0.0.1:8086/write?db=woot&precision=s"
```


heka log.
```
2015/07/16 20:41:34 Pre-loading: [LinuxStatsDecoder]
2015/07/16 20:41:34 Pre-loading: [AddStaticFields]
2015/07/16 20:41:34 Pre-loading: [InfluxdbLineEncoder]
2015/07/16 20:41:34 Pre-loading: [LogOutput]
2015/07/16 20:41:34 Pre-loading: [DashboardOutput]
2015/07/16 20:41:34 Pre-loading: [LoadAvgPoller]
2015/07/16 20:41:34 Pre-loading: [LoadAvgDecoder]
2015/07/16 20:41:34 Pre-loading: [TokenSplitter]
2015/07/16 20:41:34 Loading: [TokenSplitter]
2015/07/16 20:41:34 Pre-loading: [HekaFramingSplitter]
2015/07/16 20:41:34 Loading: [HekaFramingSplitter]
2015/07/16 20:41:34 Pre-loading: [NullSplitter]
2015/07/16 20:41:34 Loading: [NullSplitter]
2015/07/16 20:41:34 Pre-loading: [ProtobufDecoder]
2015/07/16 20:41:34 Loading: [ProtobufDecoder]
2015/07/16 20:41:34 Pre-loading: [ProtobufEncoder]
2015/07/16 20:41:34 Loading: [ProtobufEncoder]
2015/07/16 20:41:34 Loading: [AddStaticFields]
2015/07/16 20:41:34 Loading: [LoadAvgDecoder]
2015/07/16 20:41:34 Loading: [LinuxStatsDecoder]
2015/07/16 20:41:34 Loading: [InfluxdbLineEncoder]
2015/07/16 20:41:34 Loading: [LoadAvgPoller]
2015/07/16 20:41:34 Loading: [LogOutput]
2015/07/16 20:41:34 Loading: [DashboardOutput]
2015/07/16 20:41:34 Starting hekad...
2015/07/16 20:41:34 Output started: LogOutput
2015/07/16 20:41:34 Output started: DashboardOutput
2015/07/16 20:41:34 MessageRouter started.
2015/07/16 20:41:34 Input started: LoadAvgPoller
2015/07/16 20:41:39 
2015/07/16 20:41:44 
2015/07/16 20:41:49 
2015/07/16 20:41:54 
2015/07/16 20:41:59 
2015/07/16 20:42:04 
2015/07/16 20:42:09 
2015/07/16 20:42:14 
2015/07/16 20:42:19 
2015/07/16 20:42:24 
2015/07/16 20:42:29 
2015/07/16 20:42:34 
2015/07/16 20:42:39 
```

so this is normal? good :)  i was just kinda expecting to see some data.

**Comment by rafrombrc** [comment] 2015-07-17 01:05
Nope, that's not what's expected. I just tested the same config locally and am also seeing no output. Then I tried again w/ an RstEncoder and verified that the messages *do* actually contain data. I'm unfortunately about to wrap up for today, but I'll take a look tomorrow to figure out what's going on.

**Comment by steverweber** [comment] 2015-07-17 01:07
ok thanks... this sounds like a new issue.

but it does sound like the influxdb 9.0 item can be resolved. cheers!

**Comment by acesaro** [comment] 2015-07-17 04:41
I found the issue, super small typo, which was part of the cleanup work in ce0f07498dbe30676c5260e196ef9f450c5b1774.  I've submitted https://github.com/mozilla-services/heka/pull/1622 with a tested fix (using the exact config example in the ts_line_procotol.lua comments section).

**Comment by acesaro** [comment] 2015-07-17 04:48
While testing, I've also found that only base_fields are included in tags, no matter what is defined in `tag_fields`, which I believe I remember explicitly testing successfully.  I'm looking into this now to figure it out.

**Comment by acesaro** [comment] 2015-07-17 05:04
Fix for the missing tag fields that I just mentioned added to https://github.com/mozilla-services/heka/pull/1622.

**Comment by rafrombrc** [comment] 2015-07-17 16:44
Okay, #1622 has been merged. @steverweber, is it possible for you to build Heka from the versions/0.10 branch to test the latest fixes?

**Comment by steverweber** [comment] 2015-07-17 17:33
I'll try to find time this weekend.  But if the fix worked for you @rafrombrc  then I'll likely just wait for the releases. https://github.com/mozilla-services/heka/releases

**Comment by rafrombrc** [comment] 2015-07-17 19:22
Yup, it's working for me, I'm now seeing valie output, running the same config that was generating emtpy strings for me before. Hoping to have another release (either another beta or 0.10.0 final) next week, closing this issue in the meantime.

**Closed by rafrombrc** 2015-07-17 19:22 UTC

**Comment by steverweber** [comment] 2015-08-10 13:43
+1 another beta. Would like to help test this!
